name: avtarx
description: AI Avatar + Video + Chat App
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  dio: ^5.3.3
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
